const REQUEST_CONTENT = 'REQUEST_CONTENT';
const REQUEST_CONTENT_SUCCESS = 'REQUEST_CONTENT_SUCCESS';
const REQUEST_CONTENT_FAILURE = 'REQUEST_CONTENT_FAILURE';

export const content = {
    REQUEST_CONTENT,
    REQUEST_CONTENT_SUCCESS,
    REQUEST_CONTENT_FAILURE
}